name: Check change
on:
  pull_request:

jobs:
  check-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: yarn

      # This is how I was working around the inability to have renovate add the change files itself
      # - name: Add change files for renovate bot
      #   if: ${{ github.event.pull_request.user.login == 'renovate[bot]' }}
      #   run: |
      #     git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
      #     git config user.name 'Renovate Bot'
      #     git config user.email 'bot@renovateapp.com'
      #     yarn change --type patch --message "$PR_TITLE"
      #     git push origin HEAD:$GITHUB_HEAD_REF
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PR_TITLE: ${{ github.event.pull_request.title }}
      # - name: Add change files for renovate bot

      - run: yarn checkchange
